views:
  - name: horasreportadas
    cubes:
      - join_path: fact_horasreportadas
        includes:
          - regdate
          - count
          - hours
          - cost
      - join_path: dim_people
        includes:
          - fullname
          - role
          - username

# views:
#   - name: example_view
#
#     cubes:
#       - join_path: orders
#         includes:
#           - status
#           - created_date
#
#           - total_amount
#           - count
#
#       - join_path: orders.customers
#         prefix: true
#         includes:
#           - city
