views:
  - name: horasreportadas
    meta:
      gerencia: TI
      area: desarrollo
      autor: Ilver Anache
    cubes:
      - join_path: fact_horasreportadas
        includes:
          - regdate
          - count
          - hours
          - cost
          - sunday_week
          - fiscal_year
          - fiscal_quarter
          - fiscal_quarter_label
      - join_path: fact_horasreportadas.dim_people
        includes:
          - fullname
          - role
          - username
          - name: count
            alias: count_people

# views:
#   - name: example_view
#
#     cubes:
#       - join_path: orders
#         includes:
#           - status
#           - created_date
#
#           - total_amount
#           - count
#
#       - join_path: orders.customers
#         prefix: true
#         includes:
#           - city
